/**
 * Hand-maintained registry of USGS gauges that publish NOAA HEFS map-quantiles
 * (5/10-day exceedance forecasts) and so can compute a "chance of flooding"
 * directly — the gauge is its own predictor, threshold = its own red stage (no
 * regression).
 *
 * Kept separate from `floodPredictionConstants.json`, which is generated by an
 * analytics system and must not be hand-edited. Site IDs verified live against
 * the NWPS (USGS↔NWSLI) and HEFS map-quantiles APIs.
 *
 * Excluded: Duvall (USGS-9) has no NWRFC HEFS forecast point; the headwaters
 * metagage (USGS-SF17/USGS-NF10/USGS-MF11) is a synthetic flow-sum with no single
 * NOAA site — its component forks are covered individually below.
 */
export interface DirectGauge {
  /** Floodzilla locationId, e.g. "USGS-38". */
  gaugeId: string;
  /** USGS site number for the rating table (flow → gage height). */
  usgsSiteId: string;
  /** NWSLI / NOAA HEFS location id for the map-quantiles. */
  noaaSiteId: string;
  name: string;
}

export const DIRECT_GAUGES: DirectGauge[] = [
  { gaugeId: "USGS-38", usgsSiteId: "12144500", noaaSiteId: "SQUW1", name: "Falls" },
  { gaugeId: "USGS-22", usgsSiteId: "12149000", noaaSiteId: "CRNW1", name: "Carnation" },
  { gaugeId: "USGS-SH5", usgsSiteId: "12150800", noaaSiteId: "MROW1", name: "Monroe" },
  { gaugeId: "USGS-SF17", usgsSiteId: "12143400", noaaSiteId: "GARW1", name: "South Fork" },
  { gaugeId: "USGS-MF11", usgsSiteId: "12141300", noaaSiteId: "TANW1", name: "Middle Fork" },
  { gaugeId: "USGS-NF10", usgsSiteId: "12142000", noaaSiteId: "SNQW1", name: "North Fork" },
];

/** The direct-gauge entry for a locationId, or null when it isn't one. */
export function getDirectGaugeConstants(locationId?: string): DirectGauge | null {
  if (!locationId) {
    return null;
  }
  return DIRECT_GAUGES.find((g) => g.gaugeId === locationId) ?? null;
}
